name: Github Action Demo 2
on: push
jobs:
  action-demo:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Print index1.html
        run: cat index1.html
 
        
  
